### PR TITLE
feat: tls-psk

### PR DESCRIPTION
**Pull request by jclab-joseph**
Support TLS-PSK

### CODE REVIEW

**Comment by brunoos** [comment]
Hi @jclab-joseph, thanks for the PR.
But the code has some issues.

**Comment by jclab-joseph** [comment]
@brunoos Please let me know what is wrong with the source.

**Comment by brunoos** [comment]
I think that the main point is your code is truncating the callback's response to maximum value.

Would be better to pass this information to the callback and let it deal with the size. After, if the return is bigger than the maximum, trigger an error.

The idea is just connect the things...

**Comment by brunoos** [comment]
@jclab-joseph I created a branch `tls-psk`, imported your code and made some fixes.
Thanks

**Pull request closed without merging**
