### PR TITLE
Update rockspec to fix Windows build

### PR DESCRIPTION
**Pull request by Tieske**
I ran into issues for the windows build;

- winsock dependency missing
- external dependencies not defined

fix in the added rockspec.

### CODE REVIEW

**Comment by Tieske** [comment]
I updated the winsock version, and defines. So that's fixed, but I cannot update the library names without the build failing on MinGW;

````
mingw32-gcc -shared -o ssl.dll src/x509.o src/context.o src/ssl.o src/luasocket/buffer.o src/luasocket/io.o src/luasocke
t/timeout.o src/luasocket/wsocket.o -Lc:/external/lib -llibeay32 -lssleay32 -lws2_32 C:/Program Files (x86)/Lua/5.1/bin/
lua51.dll -lm
c:/mingw/bin/../lib/gcc/mingw32/4.8.1/../../../../mingw32/bin/ld.exe: cannot find -llibeay32
c:/mingw/bin/../lib/gcc/mingw32/4.8.1/../../../../mingw32/bin/ld.exe: cannot find -lssleay32
collect2.exe: error: ld returned 1 exit status

Error: Build error: Failed compiling module ssl.dll

Press any key to close this window...
````

**Comment by Tieske** [comment]
The problem is that MS compilers link against the libs, whereas MinGW links directly in the dlls, which are in the BINDIR, so hence they were not found.

Added BINDIR to the library path and now it seems to work.

@moteus can you give this rockspec a try with MS compilers and LuaRocks?

**Comment by ignacio** [comment]
Ok, Just had a go compiling @Tieske master branch with VS2008. (I had to comment out the latest additions to x509.c since it #includes sys/socket.h and other stuff which is not available).

It doesn't work, because LR generates a.def file with luaopen_ssl, and the linker errors out because it can't find that function.
So what I did is to add a dummy implementation in ssl.c:

#if defined(_MSC_VER)
/* Empty implementation to allow building with LuaRocks with MS compilers */
LSEC_API int luaopen_ssl(lua_State *L) { return 0; }
#endif

It works as long as Lua modules takes precedence from C modules of the same name.

**Comment by ignacio** [comment]
I've forked @Tieske repo, added the luaopen_ssl fix and got it running with AppVeyor.

https://ci.appveyor.com/project/ignacio/luasec/build/1.0.12

**Comment by ignacio** [comment]
What should be done about the error with MS compilers and LuaRocks ?

**Pull request merged**
